/* 
© 2025 Tejal Katalkar. All rights reserved. https://github.com/Tejalkatalkar
*/

--Q1. What is the total revenue generated by the bookstore?
SELECT SUM(Price) AS Total_Revenue
FROM Books_Sale;

--Q2. Which book generated the highest total revenue?
SELECT b.Title, SUM(s.Price * s.Copies_Left) AS Revenue
FROM Books_Sale s
LEFT JOIN Books_Data b 
ON s.Book_ID = b.Book_ID
GROUP BY b.Title
ORDER BY Revenue DESC
LIMIT 1;

--Q3. Which category of books sells the most copies?
SELECT b.Category, SUM(s.Copies_Left) AS Total_Copies_Sold
FROM Books_Sale s
RIGHT JOIN Books_Data b ON s.Book_ID = b.Book_ID
GROUP BY b.Category
ORDER BY Total_Copies_Sold DESC
LIMIT 5;

--Q4. Which category of books sells the most copies?
SELECT d.Month, SUM(s.Price * s.Copies_Left) AS Revenue
FROM Books_Sale s
FULL JOIN Date_Table d ON s.Date_ID = d.Date_ID
GROUP BY d.Month
ORDER BY Revenue DESC
LIMIT 1;

-- Q5. Which day of the week has the highest sales?
SELECT d.Weekday, SUM(s.Price * s.Copies_Left) AS Revenue
FROM Books_Sale s
INNER JOIN Date_Table d ON s.Date_ID = d.Date_ID
GROUP BY d.Weekday
ORDER BY Revenue DESC;

-- Q6. Which year has the highest sales?
SELECT 
    d.Year,
    SUM(s.Price * s.Copies_Left) AS Annual_Sales
FROM Books_Sale s
JOIN Date_Table d ON s.Date_ID = d.Date_ID
GROUP BY d.Year
ORDER BY d.Year;

--Q7. Which books are out of stock but had high demand?
SELECT b.Title, s.Copies_Left, s.Rating
FROM Books_Sale s
JOIN Books_Data b ON s.Book_ID = b.Book_ID
WHERE b.Stock_Status = 'Out of Stock' AND s.Rating > 4;

--Q8.What are the top 5 most expensive books (before discount)?
SELECT b.Title, s.Price
FROM Books_Sale s
INNER JOIN Books_Data b ON s.Book_ID = b.Book_ID
ORDER BY s.Price DESC
LIMIT 5;

--Q9. Ranks book ratings based on total revenue generated to identify top-performing rating groups.
SELECT 
    Rating,
    SUM(s.Price * s.Copies_Left) AS Total_Revenue,
    RANK() OVER (ORDER BY SUM(s.Price * s.Copies_Left) DESC) AS Revenue_Rank
FROM Books_Sale s
GROUP BY Rating
ORDER BY Revenue_Rank;

--10. Compare current month revenue with previous month (using LAG)
 WITH Monthly_Revenue AS (
    SELECT 
        d.Month,
        SUM(s.Price * s.Copies_Left) AS Total_Revenue
    FROM Books_Sale s
    JOIN Date_Table d ON s.Date_ID = d.Date_ID
    GROUP BY d.Month
)
SELECT Month,Total_Revenue,
    LAG(Total_Revenue) OVER (ORDER BY Month) AS Prev_Month_Revenue,
    (Total_Revenue - LAG(Total_Revenue) OVER (ORDER BY Month)) AS Revenue_Change
FROM Monthly_Revenue
ORDER BY Month;

--Q11 Ranks books based on their price to identify the highest and lowest-priced titles.
SELECT b.Title, s.Price,
RANK() OVER(ORDER BY s.Price DESC) AS Price_Rank
FROM Books_Sale s
Inner JOIN Books_Data b 
on s.Book_ID = b.Book_ID;

--Q12 Which categories have generated total revenue above 5000?
SELECT 
    b.Category, 
    SUM(s.Price * s.Copies_Left) AS Total_Revenue
FROM Books_Sale s
JOIN Books_Data b 
ON s.Book_ID = b.Book_ID
GROUP BY b.Category
HAVING SUM(s.Price * s.Copies_Left) > 5000
ORDER BY Total_Revenue DESC;

--Q13 Top publisher by total sales
SELECT 
    p.Publication,
    SUM(s.Price) AS Total_Sales
FROM Publishers p
JOIN Books_Sale s ON p.Publisher_ID = s.Publisher_ID
GROUP BY p.Publication
ORDER BY Total_Sales DESC;

--Q14 Add Total Revenue (Price × Copies Sold)
SELECT 
    d.Sales_Date,
    b.Title AS Book_Name,
    p.Publication,
    s.Rating,
    b.Stock_Status,
    (s.Price * (100 - CAST(REGEXP_REPLACE(s.Discount_Offer, '[^0-9]', '', 'g') AS NUMERIC)) / 100) AS Discounted_Price,
    (s.Price * (100 - CAST(REGEXP_REPLACE(s.Discount_Offer, '[^0-9]', '', 'g') AS NUMERIC)) / 100) * s.Copies_Left AS Total_Revenue
FROM Books_Sale s
JOIN Books_Data b ON s.Book_ID = b.Book_ID
JOIN Publishers p ON s.Publisher_ID = p.Publisher_ID
JOIN Date_Table d ON s.Date_ID = d.Date_ID
ORDER BY d.Sales_Date, b.Title;

--Q15.What books were sold on a specific date, along with their prices and remaining stock?
CREATE OR REPLACE FUNCTION GetSalesByDate(input_date DATE)
RETURNS TABLE (
    Title VARCHAR,
    Price NUMERIC,
    Copies_Left INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        b.Title, 
        s.Price, 
        s.Copies_Left
    FROM Books_Sale s
    JOIN Books_Data b ON s.Book_ID = b.Book_ID
    JOIN Date_Table d ON s.Date_ID = d.Date_ID
    WHERE d.Sales_Date = input_date;
END;
$$;

SELECT * FROM GetSalesByDate('14-09-2024');





